# 02 · ניקוי נתונים מבולגנים

<div dir="rtl">

## המטרה

החזירי עותק ללא כפילויות וללא חסרים. העמודות הן patient_id, age, bmi, sex, outcome. הסירי כפילויות לפי patient_id לפני חישוב חציונים. המירי age ו־bmi למספרים; ערכים מחוץ לטווחים 18–100 ו־10–70 ייחשבו חסרים ויושלמו בחציון. נרמלי sex ל־female/male/unknown. הסבירי מדוע ניקוי תיאורי זה אינו מתאים ללמידת חציון על כלל הנתונים לפני מודל.

זמן מומלץ: 30 דקות. קראי את `data/README.md` לפני העבודה.

## הכנה

הריצי את התא הבא. הנתונים מקומיים; אין צורך להוריד אותם שוב.

</div>

**פתרון ייחוס למורה — פתיחה רק בבקשה מפורשת.**

In [1]:
from pathlib import Path
import sys
import importlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
ROOT = Path.cwd()
if not (ROOT / "src").exists():
    ROOT = ROOT.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
from src.common import load
sns.set_theme(style="whitegrid", context="notebook")
plt.rcParams["figure.figsize"] = (8, 5)
frame = load("messy_health")
frame.head()

   patient_id      age   bmi     sex  outcome
0           1  unknown  33.6  female        1
1           2  unknown  26.6  female        0
2           3  unknown  23.3  female        1
3           4  unknown  28.1  female        0
4           5  unknown  43.1  female        1

## העבודה שלך

השלימי את `clean(frame)` בקובץ `src/ex02.py`.

כתבי לפני הקוד: מה את מצפה למצוא, ואילו נתונים חסרים כדי לפרש את התוצאה?

התא הבא בטוח להרצה: הקריאה לפונקציה נשארת בהערה עד שתשלימי אותה.

In [2]:
import solutions.ex02 as student
answer = student.clean(frame)
answer

     patient_id   age   bmi     sex  outcome
0             1  30.0  33.6  female        1
1             2  30.0  26.6  female        0
2             3  30.0  23.3  female        1
3             4  30.0  28.1  female        0
4             5  30.0  43.1  female        1
..          ...   ...   ...     ...      ...
195         196  29.0  39.4  female        1
196         197  21.0  24.3  female        0
197         198  23.0  22.9  female        1
198         199  26.0  34.8  female        1
199         200  29.0  30.9  female        1

[200 rows x 5 columns]

<details><summary>רמז ראשון — לחצי רק אחרי ניסיון עצמאי</summary>

השתמשי ב־to_numeric(errors="coerce"), ב־between וב־fillna.

</details>

<details><summary>רמז שני — איך להתקדם?</summary>

פתחי את הבדיקה `tests/test_ex02.py`, זהי ציפייה אחת, ונסי לממש אותה על טבלה קטנה. בקשי מהמורה שאלה מכוונת לפני קוד.

</details>

## חקירה והצגה

הוסיפי כאן את הגרפים וההשוואות שנדרשו במטרה. לכל גרף: כותרת, יחידות, מכנה ומשפט פרשנות. קוד ותוויות גרפים באנגלית; הדיון בעברית.

In [3]:
print("Before:", frame.isna().sum().to_dict())
print("After:", answer.isna().sum().to_dict())
display(answer.head())

Before: {'patient_id': 0, 'age': 0, 'bmi': 6, 'sex': 6, 'outcome': 0}
After: {'patient_id': 0, 'age': 0, 'bmi': 0, 'sex': 0, 'outcome': 0}

   patient_id   age   bmi     sex  outcome
0           1  30.0  33.6  female        1
1           2  30.0  26.6  female        0
2           3  30.0  23.3  female        1
3           4  30.0  28.1  female        0
4           5  30.0  43.1  female        1

## בדיקה ומשוב

בטרמינל משורש המאגר:

```bash
make check EX=02
```

כישלון עם `NotImplementedError` צפוי לפני השלמת הפונקציה. הצלחת הבדיקות מאמתת רק את חוזה הקוד; היא אינה ציון לאיכות הניתוח.

מחוון מתוך 10: קוד ובדיקות 4; גרפים וחקירה 2; מניעת הטיות/דליפה 2; פרשנות ומגבלות 2. יעד מעבר: 8 וכל בדיקות הקוד עוברות.

## דיון למורה

יש לבסס מסקנה על הפלט שהורץ. דרשי הבחנה בין קשר וסיבתיות, תיאור אוכלוסיית המדגם והערכת הכללה. אין מסקנה קלינית הנובעת מציון גבוה בלבד. בתרגיל 11 הדילול משנה את שכיחות האימון ולכן עלול לפגוע בהעברת הכיול לאוכלוסיית המבחן. בתרגיל 12 השווי ל־dummy ובחני עד כמה החלוקה הגאוגרפית משנה את ההמלצה. אין תשובה מילולית יחידה: השתמשי במחוון שבמחברת להערכת ההנמקה.